//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyProduct("SignalR")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Behzad Khosravifar 2015")]
[assembly: System.Reflection.AssemblyTrademark("SignalR")]
[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyVersion("1.0.31")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.31")]
[assembly: System.Reflection.AssemblyInformationalVersion("Compiled By Behzad")]
